version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdbprojet
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alexandre
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_projet
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: alexandre.cano@supdevinci-edu.fr
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: